// GENERATED by scripts/sync-contracts.mjs — do not edit.
  // Mirrors contracts/deployments/*.json, written by the forge deploy scripts.

  export type GeneratedDeployment = {
    chainId: number;
    simulated: boolean;
    registry: `0x${string}`;
    implementation: `0x${string}`;
    quote: `0x${string}`;
    quoteFeed: `0x${string}`;
    router?: `0x${string}`;
    targets?: `0x${string}`[];
    feeds?: `0x${string}`[];
    symbols?: string[];
  };

  export const generatedDeployments: Record<number, GeneratedDeployment> =
    {} as never;
  